### ISSUE TITLE
Relative links still not functioning correctly

### ISSUE THREAD

**Issue by timhettler** [spatools/grunt-html-build#55] opened 2015-03-30 16:09 UTC
I know this issue was raised/fixed a month ago but it is definitely still broken in the latest release. Given the following:

**src:** `src/emails/test.html`
**dest:** `build/emails/test.html`
**stylesheet:** `build/vendor/ink.css `

The output is:

`../../vendor/ink.css`

...which is one directory too far back. 

Version 0.4.1 is the last version that works correctly.

**Comment by timhettler** [comment] 2015-03-30 16:10
@corlletelab did the latest version fix your issue? Trying to figure out why this is persisting.

**Comment by jarrettmeyer** [comment] 2015-04-10 10:56
I am still seeing this problem as well. The output is `../../app/app.js`, which is one directory too far back. No matter how I configure, the directory depth is one level too deep.

**Comment by kinsho** [comment] 2015-04-22 19:16
Had this issue, had to revert back to 0.4.1 as a workaround. Hoping this gets fixed soon....

**Comment by jarrettmeyer** [comment] 2015-04-23 12:45
I was able to get it work.

Broken version:
```
htmlbuild: {
  dist: {
    src: 'index.template.html',
    dest: 'index.html'
  }
}
```

Working version:
```
htmlbuild: {
  dist: {
    src: 'html_templates/index.html',
    dest: '.'
  }
}
```

Basically, keep the template and the output in different directories, and it seems to do exactly what I want.

**Comment by rjbergerud** [comment] 2015-08-06 23:44
I'm also having this issue.  My script files are referenced as ```<script type="text/javascript" src="../../public/js/bootstrap.min.js"></script>
<script type="text/javascript" src="../../public/js/sideBar.js"></script>``` instead of ```<script type="text/javascript" src="../public/js/bootstrap.min.js"></script>
<script type="text/javascript" src="../public/js/sideBar.js"></script>```

**Comment by rjbergerud** [comment] 2015-08-10 20:02
What seems to be the issue in my script and likely the situation brought up by @timhettler comes from how the path module interprets strings as relative paths.  For instance, 

```javascript
path.relative(/Users/Labs/views/landing.ejs, /Users/Labs/public/js/bootstrap.min.js);
```
returns 

```javascript
../../public/js/bootstrap.min.js
```

while 
```javascript
path.relative(/Users/Labs/views/, /Users/Labs/public/js/bootstrap.min.js);
```
returns 
```
../public/js/bootstrap.min.js
```
which is the desired output in this situation.  The issue is that the path.relative requires absolute paths, and also (seems) treats the destination path as a directory, that is landing.ejs is thought of as a folder (https://nodejs.org/api/path.html#path_path_relative_from_to).  So as of now, the destination needs to be a directory.

**Comment by SomaticIT** [comment] 2015-10-18 16:26
Hello,
Sorry for my late answer.

@rjbergerud, @timhettler Thanks for your feedback.
The issue was when providing a _file path_ as `dest` path.
It is now fixed in release __0.5.2__ which is published to NPM.

Thanks everybody.

**Closed by SomaticIT** 2015-10-18 16:26 UTC
