### ISSUE TITLE
Suggestion: Linking to every file with HTML attributes "href" or "src"

### ISSUE THREAD

**Issue by tkoelpin** [spatools/grunt-html-build#89] opened 2017-05-14 18:04 UTC
Hello,

I want to make the project "grunt-html-build" more attractive and more comfortable. I want to replace any HTML source attributes with my predefined relative link paths.

I want to replace "<%= fixturePath %>/path/to/file.png" to "../image/file.png", depends on the source file in which order they placed into the target folder.

Many thanks in advance.

Greetings,
tkoelpin

**Comment by SomaticIT** [comment] 2017-06-26 15:14
Is it a duplicate of #88 ?

**Comment by tkoelpin** [comment] 2017-08-24 17:37
No, not really.   
I want to insert a path to an image and the script should convert it to an img-tag or to an icon-tag, like the script-section or the style section.

**Comment by SomaticIT** [comment] 2019-09-18 13:21
I closed this issue because it's too aged.
If you really want to implement this feature, you could contribute using PR.
Thanks

**Closed by SomaticIT** 2019-09-18 13:21 UTC
